create schema IF NOT EXISTS books;
use books;
CREATE TABLE IF NOT EXISTS BOOKS (BOOK_ID int(11) NOT NULL AUTO_INCREMENT,TITLE varchar(300) DEFAULT NULL,AUTHOR varchar(300) DEFAULT NULL,EDITOR varchar(300) DEFAULT NULL,PRIMARY KEY (BOOK_ID)) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=latin1;
